(function(){
'use strict';
const C=window.MasterCloud,S=window.MasterStore,E=S.escapeHtml,root=document.getElementById('adminContent');
const en=()=>window.MasterLocale?.getState().language==='en',t=(a,b)=>en()?b:a,money=n=>S.formatCurrency(n/100,'EGP');
const status={pending:['بانتظار المراجعة','Pending review'],approved:['معتمد','Approved'],rejected:['مرفوض','Rejected'],pending_payment:['بانتظار الدفع','Awaiting payment'],processing:['جاري التنفيذ','Processing'],completed:['تم التنفيذ','Completed'],cancelled:['ملغي','Cancelled']};
const label=s=>status[s]?.[en()?1:0]||s;
const date=s=>new Date(s).toLocaleString(en()?'en-GB':'ar-EG');
let data=null,tab='orders',query='',filter='all',busy=false,loadVersion=0;
function notify(text,error=false){const x=document.getElementById('adminMessage');if(x){x.textContent=text;x.className='account-message '+(error?'error':'success');x.hidden=false;x.scrollIntoView({block:'nearest'});}}
async function act(button,task){if(busy)return;busy=true;button.disabled=true;try{await task();await load();notify(t('تم حفظ التعديل.','Change saved.'));}catch(e){notify(C.errorText(e),true);}finally{busy=false;if(button.isConnected)button.disabled=false;}}
async function load(){
 const v=++loadVersion;
 try{
 const u=await C.user();if(v!==loadVersion)return;
 if(!u){root.innerHTML='<section class="auth-card"><h2>'+t('دخول الإدارة','Admin sign-in')+'</h2><p>'+t('سجل دخولك بحساب مالك المتجر، وبعدها افتح لوحة الإدارة.','Sign in with the store owner account, then return here.')+'</p><a class="primary" href="account.html">'+t('تسجيل الدخول','Sign in')+'</a></section>';return;}
 data=await C.unwrap(C.client.rpc('master_store_admin_snapshot'));if(v!==loadVersion)return;render();
 }catch(e){if(v!==loadVersion)return;root.innerHTML='<section class="auth-card"><h2>'+t('لوحة الإدارة','Admin dashboard')+'</h2><p role="alert">'+E(C.errorText(e))+'</p><a class="primary" href="account.html">'+t('حسابي','My account')+'</a><button class="ghost-btn" id="adminRetry">'+t('إعادة المحاولة','Retry')+'</button></section>';root.querySelector('#adminRetry').onclick=load;}
}
function render(){
 const stats=data.stats;
 root.innerHTML='<div class="admin-heading"><div><span class="eyebrow">MASTER STORE</span><h1>'+t('إدارة المتجر','Store management')+'</h1><p>'+t('تحكم يدوي في الطلبات والأسعار والخصومات ورصيد العملاء.','Manage orders, prices, discounts and customer balances.')+'</p></div><button id="reloadAdmin" class="ghost-btn">'+t('تحديث البيانات','Refresh data')+'</button></div><div id="adminMessage" class="account-message" role="status" hidden></div><div class="admin-stats"><article><small>'+t('إجمالي الطلبات','Total orders')+'</small><b>'+stats.orders+'</b></article><article><small>'+t('طلبات تنتظر التنفيذ','Open orders')+'</small><b>'+stats.pending_orders+'</b></article><article><small>'+t('شحن تحت المراجعة','Pending top-ups')+'</small><b>'+stats.pending_topups+'</b></article><article><small>'+t('قيمة الطلبات المكتملة','Completed order value')+'</small><b>'+money(stats.completed_sales)+'</b></article></div><div class="admin-tabs" role="group" aria-label="'+t('أقسام الإدارة','Management sections')+'">'+[['orders','الطلبات','Orders'],['topups','شحن الرصيد','Top-ups'],['plans','الباقات والأسعار','Plans & prices'],['discounts','خصومات السلة','Cart discounts'],['customers','العملاء والمحافظ','Customers & wallets'],['audit','سجل التغييرات','Change log']].map(x=>'<button class="'+(tab===x[0]?'selected':'')+'" data-tab="'+x[0]+'" aria-pressed="'+(tab===x[0])+'">'+t(x[1],x[2])+'</button>').join('')+'</div><section class="account-panel admin-workspace"><div id="adminTools"></div><div id="adminRows"></div></section>';
 root.querySelector('#reloadAdmin').onclick=()=>{if(!busy)load();};
 root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(busy)return;tab=b.dataset.tab;query='';filter='all';render();});
 tools();rows();
}
function tools(){
 const box=root.querySelector('#adminTools');
 if(['discounts','audit'].includes(tab)){box.innerHTML='';return;}
 box.innerHTML='<div class="admin-tools"><label>'+t('بحث','Search')+'<input id="adminSearch" type="search" value="'+E(query)+'" placeholder="'+t('اسم الخدمة، العميل، أو رقم الطلب','Service, customer or order ID')+'"></label>'+(['orders','topups'].includes(tab)?'<label>'+t('الحالة','Status')+'<select id="adminFilter"><option value="all">'+t('الكل','All')+'</option>'+(tab==='orders'?['pending_payment','processing','completed','cancelled']:['pending','approved','rejected']).map(x=>'<option value="'+x+'" '+(filter===x?'selected':'')+'>'+label(x)+'</option>').join('')+'</select></label>':'')+'</div><p class="admin-help">'+t(tab==='plans'?'السعر بالجنيه المصري. الحفظ يظهر على المتجر والسلة؛ الطلبات القديمة تحتفظ بسعرها.':tab==='customers'?'تعديل الرصيد يحتاج سببًا، وكل حركة بتظهر في محفظة العميل وسجل الإدارة.':'راجع التحويل فعليًا قبل اعتماد الدفع. القائمة تعرض أحدث 500 سجل.',tab==='plans'?'Prices are in EGP. Saved changes appear in the store and cart; existing orders keep their price.':tab==='customers'?'Balance changes require a reason and appear in the customer ledger and admin log.':'Verify transfers before approval. Showing the latest 500 records.')+'</p>';
 box.querySelector('#adminSearch').oninput=e=>{query=e.target.value;rows();};
 box.querySelector('#adminFilter')?.addEventListener('change',e=>{filter=e.target.value;rows();});
}
function matching(x){return (!query||JSON.stringify(x).toLowerCase().includes(query.toLowerCase()))&&(filter==='all'||x.status===filter);}
function rows(){
 const box=root.querySelector('#adminRows');
 if(tab==='discounts'){discounts(box);return;}
 if(tab==='audit'){box.innerHTML='<h2>'+t('آخر 100 تعديل','Latest 100 changes')+'</h2>'+data.audit.map(x=>'<details class="admin-log"><summary>'+E(({master_store_plans:t('تعديل باقة','Plan change'),master_store_discount_rules:t('تعديل الخصومات','Discount change'),master_store_topups:t('مراجعة شحن','Top-up review'),master_store_orders:t('تحديث طلب','Order update'),wallet_adjustment:t('تعديل رصيد','Balance adjustment')})[x.action]||x.action)+' · '+date(x.created_at)+'</summary><small class="record-id">'+E(x.target)+' · '+E(x.admin_id)+'</small><div class="admin-diff"><div><b>'+t('قبل','Before')+'</b><pre>'+E(JSON.stringify(x.before_data,null,2)||'—')+'</pre></div><div><b>'+t('بعد','After')+'</b><pre>'+E(JSON.stringify(x.after_data,null,2))+'</pre></div></div></details>').join('');if(!data.audit.length)box.innerHTML+='<p>'+t('لسه مفيش تعديلات.','No changes yet.')+'</p>';return;}
 const items=data[tab].filter(matching);
 if(!items.length){box.innerHTML='<p>'+t('مفيش نتائج.','No matching records.')+'</p>';return;}
 if(tab==='orders'){
 box.innerHTML=items.map(x=>'<article class="admin-record"><div class="admin-record-head"><h3>'+E(x.product)+' · '+money(x.amount_piasters)+'</h3><span class="subtle-tag">'+E(label(x.status))+'</span></div><p>'+E(x.plan)+' × '+x.quantity+'</p>'+(x.discount_piasters?'<p class="cart-saving">'+t('خصم السلة: ','Cart discount: ')+money(x.discount_piasters)+'</p>':'')+'<p>'+E(x.customer.name)+' · '+E(x.customer.email)+' · '+E(x.customer.phone)+'</p><small class="record-id">'+E(x.id)+'</small><small>'+date(x.created_at)+' · '+E(x.payment)+'</small>'+(!['completed','cancelled'].includes(x.status)?'<div class="admin-actions">'+(x.status==='pending_payment'?'<button class="ghost-btn" data-order="'+x.id+'" data-status="processing">'+t('تأكيد وصول الدفع','Confirm payment received')+'</button>':'')+(x.status==='processing'?'<button class="primary" data-order="'+x.id+'" data-status="completed">'+t('تم التنفيذ','Mark completed')+'</button>':'')+'<button class="ghost-btn" data-order="'+x.id+'" data-status="cancelled">'+t('إلغاء الطلب','Cancel order')+'</button></div>':'')+'</article>').join('');
 box.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{const x=data.orders.find(x=>x.id===b.dataset.order);if(!confirm(t(b.dataset.status==='cancelled'?'تأكيد إلغاء '+x.product+'؟ '+(x.payment==='wallet'?'هيتم استرجاع '+money(x.amount_piasters)+' للمحفظة.':'الدفع الخارجي يستلزم متابعة الاسترداد مع العميل.'):b.dataset.status==='processing'?'أكدت وصول الدفع فعليًا؟':'تم تسليم الخدمة للعميل؟',b.dataset.status==='cancelled'?'Cancel this order? Wallet payments are refunded automatically. External refunds require manual follow-up.':b.dataset.status==='processing'?'Have you verified payment was received?':'Has the service been delivered?')))return;act(b,()=>C.unwrap(C.client.rpc('master_store_review_order',{request_id:x.id,new_status:b.dataset.status})));});return;
 }
 if(tab==='topups'){
 box.innerHTML=items.map(x=>'<article class="admin-record"><div class="admin-record-head"><h3>'+money(x.amount_piasters)+' · '+E(x.payment)+'</h3><span>'+E(label(x.status))+'</span></div><p>'+E(data.customers.find(c=>c.user_id===x.user_id)?.email||x.user_id)+'</p><p>'+t('رقم التحويل: ','Transfer reference: ')+E(x.reference)+'</p><small class="record-id">'+E(x.id)+'</small><small>'+date(x.created_at)+'</small>'+(x.status==='pending'?'<div class="admin-actions"><button class="primary" data-topup="'+x.id+'" data-approve="true">'+t('اعتماد وإضافة الرصيد','Approve and credit balance')+'</button><button class="ghost-btn" data-topup="'+x.id+'" data-approve="false">'+t('رفض','Reject')+'</button></div>':'')+'</article>').join('');
 box.querySelectorAll('[data-topup]').forEach(b=>b.onclick=()=>{const x=data.topups.find(x=>x.id===b.dataset.topup),approve=b.dataset.approve==='true';if(!confirm(t(approve?'تأكدت من وصول '+money(x.amount_piasters)+'؟ الاعتماد هيضيف المبلغ للمحفظة.':'تأكيد رفض طلب الشحن؟',approve?'Confirm the transfer was received? This credits the wallet.':'Reject this top-up?')))return;act(b,()=>C.unwrap(C.client.rpc('master_store_review_topup',{request_id:x.id,approve})));});return;
 }
 if(tab==='plans'){
 box.innerHTML=items.map(x=>'<form class="admin-record admin-plan" data-product="'+E(x.product_id)+'" data-plan="'+x.plan_index+'"><div><h3>'+E(x.product_name)+'</h3><p>'+E(x.plan_name)+' · '+E(x.duration)+'</p><small>'+t(x.admin_overridden?'تم تعديله يدويًا':'السعر الحالي',x.admin_overridden?'Manually updated':'Current price')+'</small></div><div class="admin-plan-fields"><label>'+t('السعر بالجنيه','Price in EGP')+'<input name="price" type="number" required min="1" max="1000000" step="0.01" value="'+x.price_piasters/100+'"></label><label>'+t('أقصى كمية','Maximum quantity')+'<input name="quantity" type="number" required min="1" max="5" step="1" value="'+x.max_quantity+'"></label><label class="admin-check"><input name="available" type="checkbox" '+(x.available?'checked':'')+'>'+t('متاح للطلب','Available')+'</label><button class="primary" type="submit">'+t('حفظ الباقة','Save plan')+'</button></div></form>').join('');
 box.querySelectorAll('form').forEach(f=>f.onsubmit=e=>{e.preventDefault();const x=data.plans.find(x=>x.product_id===f.dataset.product&&x.plan_index===+f.dataset.plan),price=Math.round(Number(f.elements.price.value)*100),qty=Number(f.elements.quantity.value),available=f.elements.available.checked;if(!confirm(t('حفظ '+x.product_name+' — '+x.plan_name+' بسعر '+money(price)+'؟','Save this plan at '+money(price)+'?')))return;act(f.querySelector('button'),()=>C.unwrap(C.client.rpc('master_store_admin_plan',{product_key:x.product_id,plan_number:x.plan_index,price,is_available:available,quantity_limit:qty,expected_version:x.updated_at})));});return;
 }
 if(tab==='customers'){
 box.innerHTML=items.map(x=>'<article class="admin-record"><div class="admin-record-head"><h3>'+E(x.name||x.email)+'</h3><b>'+money(x.balance_piasters)+'</b></div><p>'+E(x.email)+' · '+E(x.phone)+'</p><small class="record-id">'+E(x.user_id)+'</small><details><summary>'+t('تعديل الرصيد يدويًا','Adjust balance manually')+'</summary><form class="admin-adjust" data-customer="'+E(x.user_id)+'"><label>'+t('الحركة','Action')+'<select name="direction"><option value="1">'+t('إضافة رصيد','Credit balance')+'</option><option value="-1">'+t('خصم رصيد','Debit balance')+'</option></select></label><label>'+t('المبلغ بالجنيه','Amount in EGP')+'<input name="amount" type="number" required min="0.01" max="50000" step="0.01"></label><label>'+t('سبب التعديل','Reason')+'<input name="reason" type="text" required minlength="6" maxlength="200"></label><button class="primary" type="submit">'+t('تأكيد تعديل الرصيد','Confirm balance adjustment')+'</button></form></details></article>').join('');
 box.querySelectorAll('form').forEach(f=>{let id=crypto.randomUUID();f.onchange=()=>{id=crypto.randomUUID();};f.onsubmit=e=>{e.preventDefault();const x=data.customers.find(x=>x.user_id===f.dataset.customer),amount=Math.round(Number(f.elements.amount.value)*100)*Number(f.elements.direction.value),reason=f.elements.reason.value.trim();if(!confirm(t((amount>0?'إضافة ':'خصم ')+money(Math.abs(amount))+' '+(amount>0?'لحساب ':'من حساب ')+x.email+'؟\n'+reason,(amount>0?'Credit ':'Debit ')+money(Math.abs(amount))+' — '+x.email+'?\n'+reason)))return;act(f.querySelector('button'),()=>C.unwrap(C.client.rpc('master_store_admin_adjust_wallet',{request_id:id,customer_id:x.user_id,amount,reason})));};});return;
 }
}
function discounts(box){
 const d=data.discounts;
 box.innerHTML='<h2>'+t('خصم حسب عدد الاشتراكات','Discount by subscription count')+'</h2><p>'+t('العدد يشمل نفس الخدمة والخدمات المختلفة. النسب لازم تزيد أو تفضل ثابتة مع زيادة العدد. الخصم بيتطبق على الطلبات الجديدة فقط.','Same and different services count alike. Rates must stay equal or rise with quantity. Changes apply to new orders only.')+'</p><form id="discountForm" class="admin-discounts">'+[['two','اشتراكين','2 subscriptions'],['three','٣ اشتراكات','3 subscriptions'],['four','٤ اشتراكات','4 subscriptions'],['five','٥ أو أكتر','5 or more']].map(x=>'<label>'+t(x[1],x[2])+' (%)<input type="number" name="'+x[0]+'" min="0" max="50" step="1" required value="'+d[x[0]]+'"></label>').join('')+'<button class="primary" type="submit">'+t('حفظ نسب الخصم','Save discount rates')+'</button></form>';
 const f=box.querySelector('form');f.onsubmit=e=>{e.preventDefault();const vals=['two','three','four','five'].map(x=>Number(f.elements[x].value));if(vals.some((x,i)=>!Number.isInteger(x)||x<0||x>50||(i&&x<vals[i-1]))){notify(t('راجع النسب: من ٠ إلى ٥٠٪ وبتزيد مع العدد.','Use whole percentages from 0 to 50, increasing with quantity.'),true);return;}if(!confirm(t('تأكيد تحديث الخصومات إلى '+vals.join('٪ / ')+'٪؟','Update discount rates to '+vals.join('% / ')+'%?')))return;act(f.querySelector('button'),()=>C.unwrap(C.client.rpc('master_store_admin_discounts',{two:vals[0],three:vals[1],four:vals[2],five:vals[3],expected_version:d.updated_at})));};
}
if(!C?.ready){root.textContent=t('تعذر تحميل الإدارة. حدث الصفحة.','Could not load administration. Refresh the page.');return;}
root.innerHTML='<p role="status">'+t('جاري التحقق من صلاحيات الإدارة…','Checking administrator permissions…')+'</p>';load();
C.client.auth.onAuthStateChange(e=>{if(e==='SIGNED_OUT'){data=null;load();}});
document.addEventListener('masterstore:localechange',()=>{if(data&&!busy)render();});
})();
