import {test} from 'node:test';
import assert from 'node:assert/strict';
import worker,{verifySignature,extractEvents,BotState,defaults,validateProvider,generateReply,isActive} from '../src/worker.js';
class Storage{map=new Map();alarm=null;async get(k){return structuredClone(this.map.get(k));}async put(k,v){if(typeof k==='object'){for(const[a,b]of Object.entries(k))this.map.set(a,structuredClone(b));}else this.map.set(k,structuredClone(v));}async deleteAll(){this.map.clear();}async getAlarm(){return this.alarm;}async setAlarm(v){this.alarm=v;}async deleteAlarm(){this.alarm=null;}}
function fixture(){const objects=new Map();const env={ADMIN_TOKEN:'test-password',OPENAI_API_KEY:'test-api',GRAPH_VERSION:'v25.0'};env.STATE={idFromName:x=>x,get(id){if(!objects.has(id))objects.set(id,new BotState({storage:new Storage(),blockConcurrencyWhile:fn=>fn()},env));const o=objects.get(id);return{fetch:r=>o.fetch(r)};}};return{env,objects};}
async function call(env,path,data,method='GET',auth=true){return worker.fetch(new Request('https://bot.example'+path,{method,headers:{...(auth?{authorization:'Bearer '+env.ADMIN_TOKEN}:{}),...(data?{'content-type':'application/json'}:{})},body:data?JSON.stringify(data):undefined}),env);}
async function internal(env,name,path,data){return env.STATE.get(name).fetch(new Request('https://internal'+path,{method:data?'POST':'GET',body:data?JSON.stringify(data):undefined}));}
async function create(env,name='متجر'){const r=await call(env,'/api/clients',{...defaults,businessName:name},'POST');assert.equal(r.status,201);return r.json();}
async function sign(raw,secret='secret'){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return 'sha256='+Buffer.from(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(raw))).toString('hex');}
test('HMAC verifies genuine payload and rejects tampering',async()=>{const raw='{"hello":1}';assert.equal(await verifySignature(raw,await sign(raw),'secret'),true);assert.equal(await verifySignature(raw+' ',await sign(raw),'secret'),false);assert.equal(await verifySignature(raw,null,'secret'),false);});
test('webhooks ignore echoes, wrong page and malformed sender',()=>{const e={sender:{id:'456'},recipient:{id:'123'},timestamp:Date.now(),message:{mid:'m1',text:'مرحبا'}};assert.equal(extractEvents({object:'page',entry:[{id:'123',messaging:[e,{...e,message:{mid:'m2',is_echo:true}}]}]},'123').length,1);assert.equal(extractEvents({object:'page',entry:[{id:'999',messaging:[e]}]},'123').length,0);});
test('client CRUD is gated and rejects invalid values',async()=>{const{env}=fixture();assert.equal((await call(env,'/api/clients',null,'GET',false)).status,401);assert.equal((await call(env,'/api/clients',{...defaults,businessName:'',dailyReplies:-1},'POST')).status,400);});
test('creation and updates persist independent customer knowledge and subscriptions',async()=>{const{env}=fixture();const a=await create(env,'الأول'),b=await create(env,'الثاني');assert.notEqual(a.id,b.id);const r=await call(env,'/api/clients/'+a.id,{...a,knowledge:'سعر المنتج 250 جنيه',monthlyPrice:500},'PUT');assert.equal(r.status,200);const rows=await(await call(env,'/api/clients')).json();assert.equal(rows.length,2);assert.equal(rows.find(c=>c.id===a.id).knowledge,'سعر المنتج 250 جنيه');assert.equal(rows.find(c=>c.id===b.id).knowledge,'');});
test('per-tenant quotas and token counters do not leak',async()=>{const{env}=fixture();for(let i=0;i<2;i++)await internal(env,'tenant:a','/reserve',{daily:2,monthly:3});const blocked=await(await internal(env,'tenant:a','/reserve',{daily:2,monthly:3})).json();assert.equal(blocked.allowed,false);assert.equal((await(await internal(env,'tenant:b','/usage')).json()).monthly,0);await internal(env,'tenant:a','/record',{tokens:40,preview:true});assert.equal((await(await internal(env,'tenant:a','/usage')).json()).tokens,40);});
test('provider validates HTTPS and blocks local hosts, raw IPs and credential URLs',()=>{const v={baseURL:'https://gateway.example/v1',model:'model-from-provider',outputParameter:'max_tokens'};assert.equal(validateProvider(v),true);for(const url of ['http://gateway.example/v1','https://localhost/v1','https://127.0.0.1/v1','https://user:password@gateway.example/v1','https://internal.local/v1'])assert.equal(validateProvider({...v,baseURL:url}),false);});
test('provider compatibility uses saved intermediary endpoint, model and output limit',async()=>{const{env}=fixture();await call(env,'/api/settings',{baseURL:'https://gateway.example/v1/',model:'my-model',outputParameter:'max_tokens'},'POST');const old=globalThis.fetch;let captured;globalThis.fetch=async(url,o)=>{captured={url,body:JSON.parse(o.body),headers:o.headers};return new Response(JSON.stringify({choices:[{message:{content:'أهلًا'}}],usage:{total_tokens:12}}));};try{const r=await generateReply(env,{...defaults,businessName:'متجر'},'مرحبا');assert.equal(r.answer,'أهلًا');assert.equal(captured.url,'https://gateway.example/v1/chat/completions');assert.equal(captured.body.model,'my-model');assert.equal(captured.body.max_tokens,250);assert.equal(captured.headers.authorization,'Bearer test-api');}finally{globalThis.fetch=old;}});
test('without API key customer creation works and preview refuses with zero usage',async()=>{const{env}=fixture();delete env.OPENAI_API_KEY;const c=await create(env);const r=await call(env,'/api/clients/'+c.id+'/preview',{text:'hello'},'POST');assert.equal(r.status,409);const usage=await(await internal(env,'tenant:'+c.id,'/usage')).json();assert.equal(usage.monthly,0);});
test('preview stays inside dashboard and counts actual returned tokens',async()=>{const{env}=fixture();const c=await create(env);const old=globalThis.fetch;let calls=0;globalThis.fetch=async url=>{assert.ok(String(url).includes('openai'));calls++;return new Response(JSON.stringify({choices:[{message:{content:'رد تجريبي'}}],usage:{total_tokens:25}}));};try{const r=await call(env,'/api/clients/'+c.id+'/preview',{text:'مرحبا'},'POST');assert.equal(r.status,200);assert.equal(calls,1);const u=await(await internal(env,'tenant:'+c.id,'/usage')).json();assert.equal(u.tokens,25);assert.equal(u.previews,1);}finally{globalThis.fetch=old;}});
test('linking remains closed for unconnected clients',async()=>{const{env}=fixture();const c=await create(env);assert.equal((await call(env,'/webhook/'+c.id)).status,503);});
test('cross-origin writes rejected',async()=>{const{env}=fixture();const r=await worker.fetch(new Request('https://bot.example/api/clients',{method:'POST',headers:{origin:'https://evil.example',authorization:'Bearer test-password'},body:JSON.stringify({...defaults,businessName:'متجر'})}),env);assert.equal(r.status,403);});
test('login cookie works, expires and rate limits bad passwords',async()=>{const{env}=fixture();const r=await call(env,'/api/login',{password:'test-password'},'POST',false);assert.equal(r.status,200);const cookie=r.headers.get('set-cookie');assert.match(cookie,/HttpOnly; Secure; SameSite=Strict/);const r2=await worker.fetch(new Request('https://bot.example/api/clients',{headers:{cookie}}),env);assert.equal(r2.status,200);for(let i=0;i<9;i++)await call(env,'/api/login',{password:'wrong'},'POST',false);assert.equal((await call(env,'/api/login',{password:'wrong'},'POST',false)).status,429);});
test('expired subscriptions cannot reply',()=>{assert.equal(isActive({...defaults,enabled:true,status:'active',expiresAt:'2020-01-01'}),false);assert.equal(isActive({...defaults,enabled:true,status:'active'}),true);});
test('conversation state is isolated and duplicate receipt stores once',async()=>{const{env,objects}=fixture();const e={id:'m1',sender:'123',text:'hello',timestamp:Date.now(),tenantId:'a'};for(let i=0;i<2;i++)await internal(env,'contact:a:123','/enqueue',e);await internal(env,'contact:b:123','/enqueue',{...e,tenantId:'b'});assert.equal((await objects.get('contact:a:123').s.get('pending')).length,1);await internal(env,'contact:a:123','/pause',{paused:true});assert.equal(await objects.get('contact:b:123').s.get('paused'),undefined);});
