import {test} from 'node:test';
import assert from 'node:assert/strict';
import worker,{verifySignature,extractEvents,BotState} from '../src/worker.js';
const encoder=new TextEncoder();
async function sign(raw){const key=await crypto.subtle.importKey('raw',encoder.encode('secret'),{name:'HMAC',hash:'SHA-256'},false,['sign']);return 'sha256='+Buffer.from(await crypto.subtle.sign('HMAC',key,encoder.encode(raw))).toString('hex');}
class Storage{
 map=new Map(); alarm=null;
 async get(k){return structuredClone(this.map.get(k));}
 async put(k,v){if(typeof k==='object'){for(const [a,b]of Object.entries(k))this.map.set(a,structuredClone(b));}else this.map.set(k,structuredClone(v));}
 async deleteAll(){this.map.clear();}
 async getAlarm(){return this.alarm;}
 async setAlarm(v){this.alarm=v;}
 async deleteAlarm(){this.alarm=null;}
}
function fixture(){
 const objects=new Map();const env={OPENAI_API_KEY:'fake',META_APP_SECRET:'secret',PAGE_ACCESS_TOKEN:'fake',PAGE_ID:'123',VERIFY_TOKEN:'verify',ADMIN_TOKEN:'admin',GRAPH_VERSION:'v25.0'};
 env.STATE={idFromName:x=>x,get(id){if(!objects.has(id)){const storage=new Storage();objects.set(id,new BotState({storage,blockConcurrencyWhile:fn=>fn()},env));}const object=objects.get(id);return {fetch:(input,init)=>object.fetch(input instanceof Request?input:new Request(input,init))};}};
 return {env,objects};
}
const request=(path,data)=>new Request('https://internal'+path,{method:data?'POST':'GET',body:data?JSON.stringify(data):undefined});
test('HMAC rejects tampered body and missing signature',async()=>{const raw='{"hello":1}';assert.equal(await verifySignature(raw,await sign(raw),'secret'),true);assert.equal(await verifySignature(raw+' ',await sign(raw),'secret'),false);assert.equal(await verifySignature(raw,null,'secret'),false);});
test('extract ignores wrong pages and echo events',()=>{const event={sender:{id:'456'},recipient:{id:'123'},timestamp:Date.now(),message:{mid:'m1',text:'مرحبا'}};assert.equal(extractEvents({object:'page',entry:[{id:'123',messaging:[event,{...event,message:{mid:'m2',is_echo:true}}]}]},'123').length,1);assert.equal(extractEvents({object:'page',entry:[{id:'999',messaging:[event]}]},'123').length,0);});
test('verification and admin are locked',async()=>{const {env}=fixture();assert.equal((await worker.fetch(new Request('https://x/webhook?hub.mode=subscribe&hub.verify_token=wrong'),env)).status,403);assert.equal(await(await worker.fetch(new Request('https://x/webhook?hub.mode=subscribe&hub.verify_token=verify&hub.challenge=42'),env)).text(),'42');assert.equal((await worker.fetch(new Request('https://x/admin/config'),env)).status,401);});
test('signed webhook stored once, bad signatures rejected',async()=>{const {env,objects}=fixture();const raw=JSON.stringify({object:'page',entry:[{id:'123',messaging:[{sender:{id:'456'},recipient:{id:'123'},timestamp:Date.now(),message:{mid:'m1',text:'hello'}}]}]});const signature=await sign(raw);for(let i=0;i<2;i++){const r=await worker.fetch(new Request('https://x/webhook',{method:'POST',headers:{'x-hub-signature-256':signature},body:raw}),env);assert.equal(r.status,200);}assert.equal((await objects.get('contact:456').s.get('pending')).length,1);assert.equal((await worker.fetch(new Request('https://x/webhook',{method:'POST',body:raw}),env)).status,403);});
test('daily cap reserves atomically and disabled bot spends nothing',async()=>{const {env}=fixture();const s=env.STATE.get('settings');assert.equal((await(await s.fetch(request('/reserve',{}))).json()).allowed,false);await s.fetch(request('/config',{enabled:true,dailyReplies:1}));assert.equal((await(await s.fetch(request('/reserve',{}))).json()).allowed,true);assert.equal((await(await s.fetch(request('/reserve',{}))).json()).allowed,false);});
test('AI reply sends to Meta and human request pauses without AI',async()=>{const {env,objects}=fixture();await env.STATE.get('settings').fetch(request('/config',{enabled:true,knowledge:'العمل من 9 إلى 5',businessName:'تجربة',dailyReplies:100,maxOutputTokens:250}));env.STATE.get('contact:456');const contact=objects.get('contact:456');const calls=[];const old=globalThis.fetch;globalThis.fetch=async(url,options)=>{calls.push({url:String(url),body:JSON.parse(options.body)});return new Response(JSON.stringify(String(url).includes('openai')?{choices:[{message:{content:'مواعيدنا من 9 إلى 5'}}]}:{message_id:'sent'}),{status:200});};try{await contact.fetch(request('/enqueue',{id:'one',sender:'456',text:'مواعيدكم؟',timestamp:Date.now()}));await contact.alarm();assert.equal(calls.length,2);assert.equal(calls[1].body.messaging_type,'RESPONSE');assert.equal((await contact.s.get('history')).length,2);await contact.fetch(request('/enqueue',{id:'two',sender:'456',text:'عايز موظف',timestamp:Date.now()}));await contact.alarm();assert.equal(calls.length,3);assert.equal(await contact.s.get('paused'),true);await contact.fetch(request('/enqueue',{id:'three',sender:'456',text:'hello',timestamp:Date.now()}));await contact.alarm();assert.equal(calls.length,3);}finally{globalThis.fetch=old;}});
test('old messages do not send beyond response window',async()=>{const {env,objects}=fixture();await env.STATE.get('settings').fetch(request('/config',{enabled:true,dailyReplies:100}));env.STATE.get('contact:456');const c=objects.get('contact:456');await c.fetch(request('/enqueue',{id:'old',sender:'456',text:'hello',timestamp:Date.now()-25*3600000}));const old=globalThis.fetch;globalThis.fetch=()=>{throw Error('must not call');};try{await c.alarm();assert.equal(await c.s.get('history'),undefined);}finally{globalThis.fetch=old;}});
