const CATALOG=[
{id:'pubg',name:'PUBG Mobile',type:'mobile',label:'شدّات UC',word:'PUBG',tint:'#fff4d9',color:'#a97700',packs:['60 UC','325 UC','660 UC','1800 UC','3850 UC','8100 UC'],regions:['Global','كوريا','فيتنام'],player:true},
{id:'freefire',name:'Free Fire',type:'mobile',label:'جواهر Diamonds',word:'FREE FIRE',tint:'#f2eaff',color:'#784ac5',packs:['100 Diamonds','310 Diamonds','520 Diamonds','1060 Diamonds','2180 Diamonds'],regions:['الشرق الأوسط','أوروبا','أخرى'],player:true},
{id:'roblox',name:'Roblox',type:'cards',label:'بطاقات Roblox',logo:'roblox',tint:'#eef0f3',color:'#202939',packs:['بطاقة 10 USD','بطاقة 25 USD','بطاقة 50 USD'],regions:['حسب منطقة حسابك','الولايات المتحدة','أخرى']},
{id:'playstation',name:'PlayStation Store',type:'cards',label:'بطاقات رصيد',logo:'playstation',tint:'#eaf1ff',color:'#1f5eff',packs:['10 USD','25 USD','50 USD','100 USD','قيمة أخرى'],regions:['الولايات المتحدة','السعودية','الإمارات','المملكة المتحدة','أخرى']},
{id:'steam',name:'Steam',type:'cards',label:'بطاقات رصيد PC',logo:'steam',tint:'#edf0f4',color:'#0a1732',packs:['5 USD','10 USD','20 USD','50 USD','قيمة أخرى'],regions:['الولايات المتحدة','أوروبا','حسب عملة حسابك','أخرى']},
{id:'xbox',name:'Xbox',type:'cards',label:'بطاقات Xbox',word:'XBOX',tint:'#eaf6e5',color:'#18792b',packs:['10 USD','25 USD','50 USD','قيمة أخرى'],regions:['الولايات المتحدة','المملكة المتحدة','أخرى']},
{id:'valorant',name:'VALORANT',type:'mobile',label:'نقاط VP',logo:'riotgames',tint:'#ffecef',color:'#d33b53',packs:['475 VP','1000 VP','2050 VP','3650 VP','قيمة أخرى'],regions:['أوروبا / الشرق الأوسط','الولايات المتحدة','أخرى'],player:true},
{id:'fortnite',name:'Fortnite',type:'cards',label:'بطاقات V-Bucks',logo:'epicgames',tint:'#ebf7ff',color:'#147ca5',packs:['1000 V-Bucks','2800 V-Bucks','5000 V-Bucks','13500 V-Bucks'],regions:['الولايات المتحدة','أوروبا','أخرى']},
{id:'pcgames',name:'ألعاب PC',type:'games',label:'ألعاب رقمية للكمبيوتر',logo:'steam',tint:'#eef0ff',color:'#585ec4',packs:['اطلب لعبة بالاسم'],regions:['Steam','Epic Games','منصة أخرى'],custom:true},
{id:'consolegames',name:'ألعاب PlayStation وXbox',type:'games',label:'ألعاب رقمية للكونسول',logo:'playstation',tint:'#eef6ff',color:'#1f5eff',packs:['اطلب لعبة بالاسم'],regions:['PlayStation / أمريكي','PlayStation / سعودي','PlayStation / إماراتي','Xbox / أمريكي','أخرى'],custom:true}
];
const API='https://gmysuhoebcapigdidnnv.supabase.co/rest/v1/master_game_orders';
const KEY='sb_publishable_zHcukZ2xWD8RqrYu3i-Wzw_Kd4c8x-h';
const WA='https://wa.me/201500950624';
const $=s=>document.querySelector(s);const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let filter='all',pendingId=null,submitting=false;
function render(){const q=$('#search').value.trim().toLowerCase();const items=CATALOG.filter(p=>(filter==='all'||p.type===filter)&&`${p.name} ${p.label}`.toLowerCase().includes(q));$('#grid').innerHTML=items.map(p=>`<article class="card" style="--tint:${p.tint};--color:${p.color}"><div class="card-art"><div class="card-logo">${p.logo?`<img src="assets/${p.logo}.svg" alt="" loading="lazy" width="58" height="58">`:escapeHtml(p.word)}</div><h3 dir="auto">${escapeHtml(p.name)}</h3></div><span class="card-type">${escapeHtml(p.label)}</span><div class="card-bottom"><strong>السعر عند الطلب</strong><button class="primary" data-open="${p.id}" aria-label="شوف باقات ${escapeHtml(p.name)}">${p.custom?'اطلب لعبتك':'شوف الباقات'}</button></div></article>`).join('');$('#empty').hidden=items.length>0;}
function openProduct(id){const p=CATALOG.find(p=>p.id===id);if(!p)return;pendingId=crypto.randomUUID();$('#productContent').innerHTML=`<span class="eyebrow">${escapeHtml(p.label)}</span><h2 id="dialogTitle" dir="auto">${escapeHtml(p.name)}</h2><p class="muted">اختار تفاصيل طلبك. الفريق هيأكد السعر والتوفر على واتساب قبل الدفع.</p><form class="checkout-form" id="checkout"><label>الباقة<select name="package">${p.packs.map(v=>`<option>${escapeHtml(v)}</option>`).join('')}</select></label>${p.custom?'<label>اسم اللعبة والإصدار<input name="game" required maxlength="100" placeholder="اكتب اسم اللعبة والإصدار المطلوب"></label>':''}<label>${p.custom?'المنصة ومنطقة الحساب':'منطقة الحساب'}<select name="region">${p.regions.map(v=>`<option>${escapeHtml(v)}</option>`).join('')}</select></label>${p.player?'<label>معرّف اللاعب / Riot ID<input name="player" required maxlength="120" dir="ltr" placeholder="Player ID"></label>':''}<div class="two"><label>اسمك<input name="name" required minlength="2" maxlength="100" autocomplete="name"></label><label>رقم واتساب بكود الدولة<input name="phone" required type="tel" minlength="8" maxlength="25" pattern="[+0-9 ()-]{8,25}" dir="ltr" placeholder="+20…" autocomplete="tel"></label></div><p class="notice">ده طلب عرض سعر. الشحن أو تسليم الكود بيتم بعد تأكيد التفاصيل والدفع مع الفريق.</p><label class="check"><input type="checkbox" required><span>راجعت المنطقة ومعرّف الحساب، وموافق يتواصل معايا الفريق على واتساب بخصوص الطلب.</span></label><p class="error" id="formError" role="alert" hidden></p><button type="submit" class="primary">اطلب عرض السعر</button></form>`;$('#checkout').addEventListener('submit',e=>submitOrder(e,p));$('#productDialog').showModal();}
function readOrders(){try{return JSON.parse(localStorage.getItem('master_game_orders')||'[]')}catch{return[]}}
function saveOrder(o){try{const orders=readOrders();localStorage.setItem('master_game_orders',JSON.stringify([o,...orders.filter(v=>v.id!==o.id)].slice(0,50)));return true}catch{return false}}
function waLink(o){return WA+'?text='+encodeURIComponent(`طلب Master Game\nرقم الطلب: ${o.id}\nالمنتج: ${o.product}\nالباقة: ${o.package}\nالمنطقة: ${o.region}\n${o.player_id?'معرّف اللاعب: '+o.player_id+'\n':''}الاسم: ${o.customer_name}\nواتساب: ${o.phone}\nبرجاء تأكيد السعر والتوفر وطريقة الدفع.`)}
async function submitOrder(e,p){e.preventDefault();if(submitting)return;const f=e.target;if(!f.reportValidity())return;const d=new FormData(f);const phone=String(d.get('phone')).replace(/[^+0-9]/g,'');if(!/^\+?[0-9]{8,15}$/.test(phone)){$('#formError').hidden=false;$('#formError').textContent='اكتب رقم واتساب صحيح بكود الدولة.';return;}const name=String(d.get('name')).trim();if(name.length<2){$('#formError').hidden=false;$('#formError').textContent='اكتب اسمك من حرفين على الأقل.';return;}const o={id:pendingId,customer_name:name,phone,product:p.name,package:p.custom?String(d.get('game')).trim():d.get('package'),region:d.get('region'),player_id:d.get('player')?String(d.get('player')).trim():null};if(!o.package||(p.player&&!o.player_id))return;const b=f.querySelector('[type=submit]');b.disabled=true;b.textContent='جاري حفظ الطلب…';submitting=true;$('#formError').hidden=true;
try{const res=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',apikey:KEY,Prefer:'return=minimal'},body:JSON.stringify(o),signal:AbortSignal.timeout(15000)});if(!res.ok&&res.status!==409)throw Error('save');o.created_at=new Date().toISOString();const local=saveOrder(o);$('#productContent').innerHTML=`<div class="success"><span class="eyebrow">تم حفظ طلب عرض السعر</span><h2 id="dialogTitle">خطوة أخيرة للتأكيد</h2><p>افتح واتساب وابعت تفاصيل الطلب للفريق علشان يأكد السعر والتوفر.</p><p dir="auto">${escapeHtml(o.product)} · ${escapeHtml(o.package)}</p><p>رقم الطلب: <b dir="ltr">${escapeHtml(o.id.slice(0,8))}</b></p>${local?'':'<p>المتصفح لم يحفظ نسخة محلية. احتفظ برقم الطلب ورسالة واتساب.</p>'}<a class="primary" href="${escapeHtml(waLink(o))}" target="_blank" rel="noopener">متابعة الطلب على واتساب</a></div>`;}catch{$('#formError').hidden=false;$('#formError').innerHTML=`تعذر حفظ الطلب الآن. جرّب مرة تانية، أو <a href="${escapeHtml(waLink(o))}" target="_blank" rel="noopener">اطلب عرض السعر مباشرة على واتساب</a>.`;b.disabled=false;b.textContent='إعادة المحاولة';}finally{submitting=false;}}
document.addEventListener('click',e=>{const open=e.target.closest('[data-open]');if(open)openProduct(open.dataset.open);const close=e.target.closest('[data-close]');if(close&&!submitting)close.closest('dialog').close();const btn=e.target.closest('[data-filter]');if(btn){filter=btn.dataset.filter;document.querySelectorAll('[data-filter]').forEach(el=>{el.classList.toggle('active',el===btn);el.setAttribute('aria-pressed',String(el===btn))});render();}});
$('#search').addEventListener('input',render);$('#reset').addEventListener('click',()=>{$('#search').value='';document.querySelector('[data-filter=all]').click()});$('#myOrders').addEventListener('click',()=>{const orders=readOrders();$('#ordersList').innerHTML=orders.length?orders.map(o=>`<article class="order-item"><h3 dir="auto">${escapeHtml(o.product)}</h3><p>${escapeHtml(o.package)} · ${escapeHtml(o.region)}</p><small>${escapeHtml(new Date(o.created_at).toLocaleDateString('ar-EG'))} · رقم ${escapeHtml(o.id.slice(0,8))}</small><p>طلب عرض سعر — تابع الرد على واتساب</p><a class="ghost" href="${escapeHtml(waLink(o))}" target="_blank" rel="noopener">تابع مع الفريق</a></article>`).join(''):'<div class="empty"><h3>لسه مفيش طلبات هنا</h3><p>اختار لعبتك وباقتك، وأول طلب هيظهر هنا.</p></div>';$('#ordersDialog').showModal()});$('#productDialog').addEventListener('cancel',e=>{if(submitting)e.preventDefault()});render();
