export const channels=['messenger','whatsapp','instagram'];
export const channelOf=value=>channels.includes(value)?value:'messenger';
export const contactKey=(channel,sender)=>channel==='messenger'?sender:channel+':'+sender;
export const contactName=(tenant,channel,sender)=>'contact:'+tenant+':'+contactKey(channel,sender);
export async function getLink(env,id,channel,rpc){return rpc(env,'tenant:'+id,channel==='messenger'?'/link':'/channel-link/'+channel);}
export function configured(c,link,channel){return !!(link?.appSecret&&link?.verifyToken&&(channel==='messenger'?link.pageToken&&c.pageId:link.accessToken&&link.accountId));}
export function channelEnabled(c,link,channel){return c.enabled&&(channel==='messenger'?link?.enabled!==false:link?.enabled===true);}
export function extractChannelEvents(body,channel,link){if(channel==='instagram'){if(body.object!=='instagram')return [];return(body.entry||[]).filter(e=>String(e.id)===link.accountId).flatMap(e=>e.messaging||[]).filter(e=>String(e.recipient?.id)===link.accountId&&/^\d{1,40}$/.test(e.sender?.id||'')&&e.sender.id!==link.accountId&&e.message?.mid&&!e.message.is_echo&&!e.message.is_deleted).map(e=>({id:e.message.mid,sender:e.sender.id,text:typeof e.message.text==='string'?e.message.text.slice(0,1200):'',timestamp:e.timestamp,channel}));}if(channel==='whatsapp'){if(body.object!=='whatsapp_business_account')return [];return(body.entry||[]).filter(e=>!link.wabaId||String(e.id)===link.wabaId).flatMap(e=>e.changes||[]).filter(e=>e.field==='messages'&&e.value?.metadata?.phone_number_id===link.accountId).flatMap(e=>e.value.messages||[]).filter(e=>/^\d{1,20}$/.test(e.from||'')&&typeof e.id==='string').map(e=>({id:e.id,sender:e.from,text:(e.text?.body||e.button?.text||e.interactive?.button_reply?.title||e.interactive?.list_reply?.title||'').slice(0,1200),timestamp:Number(e.timestamp)*1000,channel}));}return [];}
export async function channelWebhook(req,env,{rpc,verifySignature}){const url=new URL(req.url),m=url.pathname.match(/^\/webhook\/([a-f0-9-]{36})\/(whatsapp|instagram)$/);if(!m)return null;const c=await rpc(env,'registry','/client/'+m[1]);if(!c)return new Response('Not found',{status:404});const channel=m[2],link=await getLink(env,c.id,channel,rpc);if(!configured(c,link,channel))return new Response('Awaiting account connection',{status:503});if(req.method==='GET'){if(url.searchParams.get('hub.mode')==='subscribe'&&url.searchParams.get('hub.verify_token')===link.verifyToken)return new Response(url.searchParams.get('hub.challenge')||'');return new Response('Forbidden',{status:403});}if(req.method!=='POST')return new Response('Method not allowed',{status:405});const raw=await req.text();if(raw.length>256000)return new Response('Too large',{status:413});if(!await verifySignature(raw,req.headers.get('x-hub-signature-256'),link.appSecret))return new Response('Forbidden',{status:403});let payload;try{payload=JSON.parse(raw)}catch{return new Response('Bad payload',{status:400})}for(const e of extractChannelEvents(payload,channel,link))await rpc(env,contactName(c.id,channel,e.sender),'/enqueue',{...e,tenantId:c.id});return new Response('EVENT_RECEIVED');}
export async function channelStorage(s,p,d,json){if(!/^\/channel-link\/(whatsapp|instagram)$/.test(p))return null;const key=p.slice(1);if(d)await s.put(key,d);return json(await s.get(key)||null);}
export async function approvedTemplates(env,link){if(!link?.accessToken||!link.wabaId)throw Error('أضف بيانات واتساب ومعرف WABA أولًا');let next=`https://graph.facebook.com/${env.GRAPH_VERSION}/${link.wabaId}/message_templates?fields=name,language,status,components&limit=100`;const rows=[];for(let page=0;next&&page<10;page++){const r=await fetch(next,{headers:{authorization:`Bearer ${link.accessToken}`},signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('تعذر تحميل قوالب واتساب');const d=await r.json();rows.push(...(d.data||[]).filter(t=>t.status==='APPROVED'&&(t.components||[]).every(c=>['BODY','FOOTER'].includes(c.type))));const cursor=d.paging?.cursors?.after;next=d.paging?.next&&cursor?`https://graph.facebook.com/${env.GRAPH_VERSION}/${link.wabaId}/message_templates?fields=name,language,status,components&limit=100&after=${encodeURIComponent(cursor)}`:null;}return rows;}
export function validateTemplate(t,templates){const found=templates.find(x=>x.name===t.name&&x.language===t.language);if(!found||!Array.isArray(t.parameters)||!t.parameters.every(p=>typeof p==='string'&&p.length<=500))return false;const text=found.components?.find(c=>c.type==='BODY')?.text||'';if(/\{\{[^0-9]/.test(text))return false;const placeholders=[...text.matchAll(/\{\{(\d+)\}\}/g)].map(x=>x[1]);return new Set(placeholders).size===t.parameters.length;}
