import {channelOf,contactKey,contactName,getLink,configured,channelEnabled,approvedTemplates,validateTemplate} from './channels.js';
const windowMs=24*3600000;
export function publicURL(value){try{if(typeof value!=='string'||value.length>1000)return false;const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&(!u.port||u.port==='443')&&u.hostname.includes('.')&&!/^[\d.]+$/.test(u.hostname)&&!u.hostname.includes(':')&&!/(^|\.)(localhost|local|internal|test|invalid)$/.test(u.hostname);}catch{return false;}}
export function validateMessage(m){return m&&['text','image','video','link'].includes(m.type)&&typeof m.text==='string'&&m.text.length<=1800&&(m.type==='text'?!!m.text.trim():publicURL(m.url));}
export function fastReply(rules,text){const value=text.trim().toLocaleLowerCase();return (rules||[]).find(r=>r.keywords.some(k=>value.includes(k.toLocaleLowerCase())));}
export async function sendMessage(env,c,link,sender,m,channel='messenger'){if(m.type!=='template'&&!validateMessage(m))throw Error('رسالة غير صحيحة');if(m.type==='template'&&channel!=='whatsapp')throw Error('القوالب لواتساب فقط');const payloads=[];let endpoint;
 if(channel==='whatsapp'){endpoint=`https://graph.facebook.com/${env.GRAPH_VERSION}/${link.accountId}/messages`;const base={messaging_product:'whatsapp',recipient_type:'individual',to:sender};if(m.type==='template')payloads.push({...base,type:'template',template:{name:m.template.name,language:{code:m.template.language},...(m.template.parameters.length?{components:[{type:'body',parameters:m.template.parameters.map(text=>({type:'text',text}))}]}:{})}});else if(['text','link'].includes(m.type))payloads.push({...base,type:'text',text:{preview_url:m.type==='link',body:[m.text,m.type==='link'?m.url:''].filter(Boolean).join('\n')}});else payloads.push({...base,type:m.type,[m.type]:{link:m.url,...(m.text?{caption:m.text.slice(0,1024)}:{})}});
 }else{endpoint=channel==='instagram'?`https://graph.instagram.com/${env.GRAPH_VERSION}/${link.accountId}/messages`:`https://graph.facebook.com/${env.GRAPH_VERSION}/${c.pageId}/messages`;const messages=[];if(['text','link'].includes(m.type))messages.push({text:[m.text,m.type==='link'?m.url:''].filter(Boolean).join('\n')});else{if(m.text)messages.push({text:m.text});messages.push({attachment:{type:m.type,payload:{url:m.url,...(channel==='messenger'?{is_reusable:true}:{})}}});}const expanded=messages.flatMap(message=>message.text?Array.from({length:Math.ceil(message.text.length/(channel==='instagram'?1000:1800))},(_,i)=>({text:message.text.slice(i*(channel==='instagram'?1000:1800),(i+1)*(channel==='instagram'?1000:1800))})):message);for(const message of expanded)payloads.push({recipient:{id:sender},...(channel==='messenger'?{messaging_type:'RESPONSE'}:{}),message});}
 const ids=[];for(const payload of payloads){const res=await fetch(endpoint,{method:'POST',headers:{authorization:`Bearer ${channel==='messenger'?link.pageToken:link.accessToken}`,'content-type':'application/json'},signal:AbortSignal.timeout(10000),body:JSON.stringify(payload)});if(!res.ok)throw Error('تعذر تأكيد إرسال الرسالة');const d=await res.json();if(d.error)throw Error('ميتا رفضت الرسالة');ids.push(d.message_id||d.messages?.[0]?.id||null);}return {accepted:true,messageIds:ids};}
export async function messagingRoute(req,env,h,userId){const {rpc,json,body,authorized,isActive}=h;const url=new URL(req.url),p=url.pathname,m=p.match(/^\/api\/(messaging|account\/messaging)\/([a-f0-9-]{36})\/(config|contacts|consent|campaigns|start|cancel|connection|activation|templates)$/);if(!m)return null;if(m[1]==='account/messaging'&&!userId)return null;if(m[1]==='messaging'&&!await authorized(req,env))return json({error:'دخول الإدارة مطلوب'},401);const c=await rpc(env,'registry','/client/'+m[2]);if(!c||userId&&c.ownerUserId!==userId)return json({error:'غير مسموح'},403);const call=(path,d)=>rpc(env,'tenant:'+c.id,path,d),action=m[3],channel=channelOf(url.searchParams.get('channel'));if(url.searchParams.has('channel')&&!['messenger','whatsapp','instagram'].includes(url.searchParams.get('channel')))return json({error:'قناة غير صحيحة'},400);const channelLink=()=>getLink(env,c.id,channel,rpc);
 if(action==='connection'){const link=await channelLink();if(req.method==='GET')return json({channel,configured:configured(c,link,channel),enabled:channelEnabled(c,link,channel),pageId:channel==='messenger'?c.pageId:link?.accountId||'',wabaId:link?.wabaId||'',webhook:url.origin+'/webhook/'+c.id+(channel==='messenger'?'':'/'+channel),hasAIKey:!!env.OPENAI_API_KEY,permissions:channel==='whatsapp'?['whatsapp_business_messaging','whatsapp_business_management']:channel==='instagram'?['instagram_business_basic','instagram_business_manage_messages']:['pages_messaging'],setup:channel==='instagram'?'حساب Instagram احترافي + Instagram Login + اشتراك messages في Webhook':channel==='whatsapp'?'رقم WhatsApp Cloud API مسجل + اشتراك التطبيق في WABA وأحداث messages':'صفحة فيسبوك + اشتراك messages'});if(userId)return json({error:'بيانات الربط يضيفها فريق الإدارة'},403);if(req.method!=='PUT')return json({error:'طريقة غير مسموحة'},405);const d=await body(req);const id=channel==='messenger'?d.pageId:d.accountId;if(!/^\d{1,40}$/.test(id||'')||!['appSecret','verifyToken',channel==='messenger'?'pageToken':'accessToken'].every(k=>typeof d[k]==='string'&&d[k].length>=16&&d[k].length<=2000)||channel==='whatsapp'&&!/^\d{1,40}$/.test(d.wabaId||''))return json({error:'راجع بيانات الربط'},400);if(channel==='messenger'){await call('/link',{appSecret:d.appSecret,pageToken:d.pageToken,verifyToken:d.verifyToken,enabled:false});await rpc(env,'registry','/client',{...c,pageId:id});}else await call('/channel-link/'+channel,{appSecret:d.appSecret,accessToken:d.accessToken,verifyToken:d.verifyToken,accountId:id,wabaId:channel==='whatsapp'?d.wabaId:'',enabled:false});return json({ok:true,configured:true,enabled:false});}
 if(action==='activation'&&req.method==='PUT'){if(userId)return json({error:'التفعيل من الإدارة بعد اختبار الربط'},403);const d=await body(req),link=await channelLink();if(typeof d.enabled!=='boolean'||!configured(c,link,channel))return json({error:'أكمل بيانات الربط أولًا'},409);if(d.enabled&&c.status!=='active')return json({error:'فعّل الاشتراك أولًا'},409);await call(channel==='messenger'?'/link':'/channel-link/'+channel,{...link,enabled:d.enabled});await rpc(env,'registry','/client',{...c,enabled:d.enabled||c.enabled});return json({enabled:d.enabled});}
 if(action==='templates'&&req.method==='GET'){if(channel!=='whatsapp')return json({error:'القوالب لواتساب فقط'},400);return json(await approvedTemplates(env,await channelLink()));}
 if(action==='config'){if(req.method==='GET')return json(await call('/messaging-config'));if(req.method!=='PUT')return json({error:'طريقة غير مسموحة'},405);const d=await body(req);if(!Array.isArray(d.rules)||d.rules.length>30||!d.rules.every(r=>typeof r.name==='string'&&r.name.length<=80&&Array.isArray(r.keywords)&&r.keywords.length>0&&r.keywords.length<=10&&r.keywords.every(k=>typeof k==='string'&&k.trim().length>=2&&k.length<=80)&&validateMessage(r.message)))return json({error:'راجع الكلمات والرسالة وروابط HTTPS'},400);return json(await call('/messaging-config',{rules:d.rules.map(r=>({name:r.name,keywords:r.keywords.map(k=>k.trim()),message:{type:r.message.type,text:r.message.text,url:r.message.url||''}}))}));}
 if(action==='contacts'&&req.method==='GET')return json((await call('/contacts')).filter(x=>channelOf(x.channel)===channel));
 if(action==='consent'&&req.method==='POST'){const d=await body(req);if(!/^\d{1,40}$/.test(d.sender||'')||typeof d.consent!=='boolean'||typeof d.note!=='string'||d.note.length>300||d.consent&&d.note.trim().length<5)return json({error:'سجّل دليل موافقة العميل'},400);return json(await call('/contact-consent',{...d,channel}));}
 if(action==='campaigns'){if(req.method==='GET')return json((await call('/campaigns')).filter(x=>channelOf(x.channel)===channel));if(req.method==='POST'){const d=await body(req);if(d.message?.type==='template'){if(channel!=='whatsapp'||!d.message.template||!validateTemplate(d.message.template,await approvedTemplates(env,await channelLink())))return json({error:'اختر قالب نصي معتمد وعدد متغيرات صحيح'},400);}else if(!validateMessage(d.message))return json({error:'راجع محتوى الرسالة'},400);if(typeof d.name!=='string'||!d.name.trim()||d.name.length>80)return json({error:'راجع محتوى الحملة'},400);return json(await call('/campaign-create',{id:crypto.randomUUID(),tenantId:c.id,channel,name:d.name,message:d.message,status:'draft',createdAt:Date.now(),results:{}}),201);}}
 if(['start','cancel'].includes(action)&&req.method==='POST'){const d=await body(req);if(!/^[a-f0-9-]{36}$/.test(d.id||''))return json({error:'معرف الحملة غير صحيح'},400);const existing=await call('/campaign-get',{id:d.id});if(!existing||channelOf(existing.channel)!==channel)return json({error:'الحملة غير موجودة في القناة'},404);if(action==='cancel')return json(await call('/campaign-cancel',d));const link=await channelLink();if(!isActive(c)||!configured(c,link,channel)||!channelEnabled(c,link,channel))return json({error:'أكمل الربط وفعّل اشتراك البوت أولًا'},409);if(existing.message.type==='template'&&!validateTemplate(existing.message.template,await approvedTemplates(env,link)))return json({error:'القالب لم يعد معتمدًا أو متغيراته تغيرت'},409);return json(await call('/campaign-start',d));}
 return json({error:'طريقة غير مسموحة'},405);
}
export async function messagingStorage(o,p,d,{json}){const s=o.s;
 if(p==='/messaging-config'){if(d)await s.put('messagingConfig',d);return json(await s.get('messagingConfig')||{rules:[]});}
 if(p==='/contacts')return json(Object.values(await s.get('contacts')||{}));
 if(p==='/contact-get')return json((await s.get('contacts')||{})[contactKey(channelOf(d.channel),d.sender)]||null);
 if(p==='/contact-update'||p==='/contact-consent'){const contacts=await s.get('contacts')||{},key=contactKey(channelOf(d.channel),d.sender);if(p==='/contact-consent'&&!contacts[key])return json({error:'المحادثة غير موجودة'},404);if(!contacts[key]&&Object.keys(contacts).length>=5000)return json({error:'وصلت لحد المحادثات'},409);const c=contacts[key]||{sender:d.sender,channel:channelOf(d.channel),lastInbound:0,consent:false};if(p==='/contact-update'){if(Number.isFinite(d.timestamp)&&d.timestamp<=Date.now()+300000)c.lastInbound=Math.max(c.lastInbound,d.timestamp);const t=(d.text||'').trim();if(/^(إلغاء|الغاء|توقف|stop)$/i.test(t)){c.consent=false;c.optedOut=true;c.note='إلغاء من العميل';}else if(/^(اشترك|اشتراك|subscribe)$/i.test(t)){c.consent=true;c.optedOut=false;c.note='موافقة برسالة من العميل';}}else{if(c.optedOut&&d.consent)return json({error:'العميل ألغى؛ يلزم أن يرسل اشترك بنفسه'},409);c.consent=d.consent;c.note=d.note;}contacts[key]=c;await s.put('contacts',contacts);return json(c);}
 if(p==='/campaign-get')return json((await s.get('campaigns')||[]).find(c=>c.id===d.id)||null);
 if(p==='/campaigns')return json(await s.get('campaigns')||[]);
 if(p.startsWith('/campaign-')){const campaigns=await s.get('campaigns')||[];let c=campaigns.find(x=>x.id===d.id);if(p==='/campaign-create'){if(campaigns.length>=100)return json({error:'الحد الأقصى ١٠٠ حملة'},409);campaigns.push(d);c=d;}else{if(!c)return json({error:'الحملة غير موجودة'},404);if(p==='/campaign-start'){if(c.status!=='draft')return json({error:'الحملة بدأت بالفعل'},409);if(campaigns.some(x=>x.status==='running'))return json({error:'توجد حملة قيد الإرسال'},409);const contacts=Object.values(await s.get('contacts')||{});c.recipients=contacts.filter(x=>channelOf(x.channel)===channelOf(c.channel)&&x.consent&&(c.message.type==='template'||Date.now()-x.lastInbound<windowMs)).map(x=>x.sender).slice(0,500);if(!c.recipients.length)return json({error:'لا توجد محادثات موافقة داخل آخر ٢٤ ساعة'},409);c.status='running';c.cursor=0;c.startedAt=Date.now();await s.setAlarm(Date.now()+100);}if(p==='/campaign-cancel')c.status='cancelled';if(p==='/campaign-result'){c.results[d.sender]=d.status;if(Object.keys(c.results).length>=c.recipients.length&&c.status==='running')c.status='completed';}}await s.put('campaigns',campaigns);return json(c);}
 return null;
}
export async function campaignAlarm(o,{rpc,isActive}){const campaigns=await o.s.get('campaigns');if(!campaigns)return false;const c=campaigns.find(x=>x.status==='running'&&x.cursor<x.recipients.length);if(!c)return true;const client=await rpc(o.env,'registry','/client/'+c.tenantId);if(!client||!isActive(client)){c.status='cancelled';await o.s.put('campaigns',campaigns);return true;}const sender=c.recipients[c.cursor++];await o.s.put('campaigns',campaigns);try{await rpc(o.env,contactName(c.tenantId,channelOf(c.channel),sender),'/enqueue',{id:'campaign:'+c.id+':'+sender,sender,tenantId:c.tenantId,channel:channelOf(c.channel),timestamp:Date.now(),outbound:c.message,campaignId:c.id});}catch{await rpc(o.env,'tenant:'+c.tenantId,'/campaign-result',{id:c.id,sender,status:'failed_or_unknown'});}if(c.cursor<c.recipients.length)await o.s.setAlarm(Date.now()+1000);return true;}
